# on:
#   push:
#     branches: [main, master]
#     workflow_dispath:
#   jobs:
#     build:
#       runs-on: ubuntu-lastest
#       steps:
#         - uses: action/checkout@v4

#         - name: build
#           uses: make build

#         - name test:
#           run: make run
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
      - run: make test
      